#!/bin/bash

set -eu

by="${1:-${USER}}"

./site build
cd _site
if git diff --quiet; then
  echo No changes to commit
else
  git add -A
  git commit -m "Built by ${by} on $(date '+%d-%b-%Y %H:%M:%S %Z')"
  git push origin master
fi
