name: steshaw-org
version: '0.1.0.0'
synopsis: Hakyll site builder for steshaw.org
category: Web
author: Steven Shaw
maintainer: steven@steshaw.org
license: MIT
license-file: LICENCE-MIT
homepage: https://steshaw.org

ghc-options:
- -O
- -Wall
- -threaded

dependencies:
- base >=4.9 && <5.0

- aeson
- aeson-pretty
- binary
- bytestring
- containers
- filepath
- hakyll
- hjsmin
- parsec
- semigroups
- text
- time
- time-locale-compat
- unordered-containers

executables:
  site:
    main: site.hs
    other-modules:
      - Abbreviations
      - Config
      - Multilang
      - YFilters
