name: steshaw-org
version: '0.1.0.0'
synopsis: Hakyll site builder for steshaw.org
category: Web
author: Steven Shaw
maintainer: steven@steshaw.org
license: MIT
license-file: LICENCE-MIT
homepage: http://steshaw.org
ghc-options:
- -O
- -Wall
- -threaded
dependencies:
- base >=4.8 && <4.9
- aeson-pretty ^>=0.7.2
- bytestring
- containers
- filepath
- hakyll >=4.7.0.0 && <= 4.8.0.0
- hjsmin
- parsec
- semigroups
- text
- time
- time-locale-compat
executables:
  site:
    main: site.hs
    other-modules:
      - Abbreviations
      - Config
      - Multilang
      - YFilters
