version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    # Cannot assign higher resource class on free plan.
    resource_class: medium
    environment:
      DEBUG: "set -x"
      NIX_PATH: "nixpkgs=channel:nixos-19.09"
      STACK_ARGS: "--jobs=2"
    steps:
      - setup_docker_engine
      - add_ssh_keys:
          fingerprints:
            - "52:ef:76:5d:82:fa:a9:be:3f:b4:da:2f:b5:f6:c4:be"
      - checkout
      - run:
          name: Setup environment
          command: |
            cat .config/environment >>$BASH_ENV
      - run:
          name: Git configuration
          command: |
            set-git-config

      - run:
          name: Create nix-config-files for cache checksum
          command: |
            mkdir -p .local/tmp
            cat .config/nix/* >.local/tmp/all-nix-config-files.txt

      - restore_cache:
          name: Restore Nix Cache
          keys:
            - nix-v1-{{ checksum ".local/tmp/all-nix-config-files.txt" }}
            - nix-v1-
      - restore_cache:
          name: Restore Stack Cache
          keys:
            - stack-v1-{{ checksum "package.yaml" }}
            - stack-v1-
      - run:
          name: Build
          command: |
            nyx build
      - save_cache:
          name: Save Stack Cache
          key: stack-v1-{{ checksum "package.yaml" }}
          paths:
            - .stack-work
            - /root/.stack
      - save_cache:
          name: Save Nix Cache
          key: nix-v1-{{ checksum ".local/tmp/all-nix-config-files.txt" }}
          paths:
            - /nix/store

      - run:
          name: Build site
          command: |
            site build
      - run:
          name: Deploy
          command: |
            nyx deploy "CircleCI (${CIRCLE_BUILD_NUM})"
