#!/usr/bin/env bash

PATH=$PWD/scripts:$PATH

export PROJECT_HOME=${PWD}
export CONFIG_HOME=${PROJECT_HOME}/.config
export NIX_CONFIG_HOME=${CONFIG_HOME}/nix

#export STACK_YAML=$ETC_DIR/stack/stack.yaml
#export STACK_ROOT=$PWD/.local/run/stack
