#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

for f in talks/*/index.org; do
  dir=$(dirname "$f")
  if [[ -d ${dir} ]]; then
    (
      echo "Building ${dir}"
      cd "${dir}"
      make
    )
  fi
done
