#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

by="${1:-${USER}}"

root_dir=$PWD
tmp_dir=.local/tmp

mkdir -p "${tmp_dir}"
cd "${tmp_dir}"

if [[ -d steshaw.github.io ]]; then
  cd steshaw.github.io
  git pull
else
  git clone --depth=1 git@github.com:steshaw/steshaw.github.io.git
  cd steshaw.github.io
fi

git ls-files -z | xargs -0 git rm --quiet

cp -r "${root_dir}"/_site/* .

git add -A

if git diff-index --quiet HEAD; then
  echo No changes to commit
else
  at=$(TZ=UTC printf '%(%d-%b-%Y %H:%M:%S %Z)T\n' -1)
  git commit -m "Deployed at ${at} by ${by}"
  git push origin master
fi
