#!/usr/bin/env bash

${DEBUG:-}

set -eu

by="${1:-Built by ${USER}}"

cd steshaw.github.io
git checkout master
git pull origin master
git ls-files -z | xargs -0 git rm

cp -r ../_site/* .

git add -A
if git diff-index --quiet HEAD; then
  echo No changes to commit
else
  git commit -m "${by} on $(date '+%d-%b-%Y %H:%M:%S %Z')"
  git push origin master
fi
