#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

package_name=$(basename "${PWD}")

has() {
  type -p "${1}" >/dev/null
}

# Use Stackage pinning when stack2cabal is available.
if has stack2cabal; then
  stack2cabal
fi

cabal2nix --no-haddock . >"${package_name}.nix"

ghc='ghc865'

cat <<! >default.nix
{ nixpkgs ? import <nixpkgs> {}, compiler ? "${ghc}" }:
nixpkgs.pkgs.haskell.packages.\${compiler}.callPackage ./${package_name}.nix { }
!

cat <<! >shell.nix
{ nixpkgs ? import <nixpkgs> {}, compiler ? "${ghc}" }:
(import ./default.nix { inherit nixpkgs compiler; }).env
!
