#!/usr/bin/env bash

${DEBUG:-}

set -eu

nixEnv=${HOME}/.nix-profile/etc/profile.d/nix.sh
if [[ -f $nixEnv ]]; then
  source ~/.nix-profile/etc/profile.d/nix.sh
fi

if which stack; then
  stack exec site watch
else
  cabal run watch
fi
