all: conquer-cabal-hell-with-nix.html notes.html

NAME1 := conquer-cabal-hell-with-nix
$(NAME1).html: $(NAME1).org
	../bin/build $(NAME1)

NAME2 := notes
$(NAME2).html: $(NAME2).org
	../bin/build $(NAME2)
