name: Build with Nix

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: 'Cache /nix/store'
        uses: actions/cache@v1
        with:
          path: /nix/store
          key: nix-store-${{ runner.OS }}-${{ hashFiles('.config/nix/*') }}
          restore-keys: |
            nix-store-${{ runner.OS }}-${{ hashFiles('.config/nix/*') }}
            nix-store-${{ runner.OS }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v13

      - name: Build
        run: |
          PATH=scripts:$PATH
          nyx gen-nix-files
          nix-build
          ./result/bin/site build

      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: 'steshaw/steshaw.github.io'
          publish_branch: 'master'
          publish_dir: '_site'
